### PR TITLE
tuple conversion list

### PR DESCRIPTION
**Pull request by kinzun**
params = [
    "22982",
    "22986"
]
(['22982', '22986'],)
['22982', '22986']

### CODE REVIEW

**Comment by gchamon** [comment]
any reason why this hasn't been merged? this issue is preventing `delete` methods from working

**Comment by lukecyca** [comment]
@gchamon I haven't had a chance to test it. If you can confirm that this works and doesn't break any other API endpoints, then I'll merge it.

**Comment by neothematrix** [comment]
hi @kinzun @gchamon!
thanks for the PR, can you please provide an example of what is currently breaking that would be fixed by this change so we can test it?
thanks!

**Comment by gchamon** [comment]
I am sorry, I think I have mistakenly taken this repo to be `py-zabbix`. Interestingly though, the same problem occurs there. I am just using the api's `do_request` instead and passing params directly, which I think applies to this repo too.

**Comment by neothematrix** [comment]
thanks @gchamon ,
can you paste an actual snippet of code causing the issue?
thanks

**Comment by neothematrix** [comment]
ciao @gchamon and @kinzun any chance you could provide some examples of code issues so that we can decide whether to merge the PR or not?
thanks!

**Comment by gchamon** [comment]
Hey there, I would have to check again, because I think I managed to solve it using do_request directly, but I also think the sdk I use is different, not this repo exactly, but `py-zabbix`, so I don't think it would be of much use.

**Comment by neothematrix** [comment]
thanks for the update, I'm closing this then.

**Pull request closed without merging**
