### PR TITLE
Fixed support of user.checkAuthentication method

### PR DESCRIPTION
**Pull request by maxgrechnev**
This method must be called without the 'auth' parameter in the JSON-RPC request

### CODE REVIEW

**Comment by maxgrechnev** [comment]
Anybody home? :)

**Comment by lukecyca** [comment]
@maxgrechnev Could you provide some context for this change? Is this a bugfix due to a recent change in the Zabbix API? Or is this merely for convenience. Do you think it requires changes to the documentation or examples?

I don't personally use Zabbix much anymore, so I rely on others to help vet changes to this project. @neothematrix?

**Comment by maxgrechnev** [comment]
No need to change docs or examples.

**Comment by neothematrix** [comment]
@maxgrechnev thanks for the fix, everything checks out!

**Comment by maxgrechnev** [comment]
@neothematrix welcome! When will it be available on PyPI?

**Comment by neothematrix** [comment]
let me check 4.0 compatibility and if nothing else is needed, we can create a new PyPi release

**Comment by neothematrix** [comment]
@maxgrechnev pypi pyzabbix 0.7.5 ready to be used! let me know if you see any issue!

**Pull request merged**
